version: '3'
services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # root password
      MYSQL_DATABASE: project # data bases name
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - dp_service_backend_network  

  spring_boot_app:
    build:
      context: ./travel
      dockerfile: Dockerfile
    image: spring_boot
    volumes:
      - ./travel/target:/app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - dp_service_backend_network  

  fast_api_app:
    build:
      context: ./python
      dockerfile: Dockerfile
    image: fast_api
    volumes:
      - ./python:/app
    ports:
      - "3000:3000"
    depends_on:
      - spring_boot_app
    networks:
      - dp_service_backend_network  

networks:
  dp_service_backend_network  :