version: '3'
services:
  airflow_app:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    image: airflow
    ports:
      - 5000:5000
    container_name: airflow
    networks:
      - dp_service_backend_network

      
  spring_boot_app:
    build:
      context: ./travel
      dockerfile: Dockerfile
    image: spring_boot
    ports:
      - "8080:8080"
    container_name: spring_boot
    networks:
      - dp_service_backend_network

  fast_api_app:
    build:
      context: ./python
      dockerfile: Dockerfile
    image: fast_api
    ports:
      - "4000:4000"
    depends_on:
      - spring_boot_app
    container_name: fast_api
    networks:
      - dp_service_backend_network

networks:
  dp_service_backend_network  :
